packages:
  - apps/*
  - packages/*
  - ../../platform/kb-labs-core/apps/*
  - ../../platform/kb-labs-core/packages/*
  - ../../platform/kb-labs-shared/apps/*
  - ../../platform/kb-labs-shared/packages/*
  - ../kb-labs-devkit
  - ../kb-labs-gateway/apps/*
  - ../kb-labs-gateway/packages/*
